# For a list of all available engines, see here:
# http://docs.codeclimate.com/article/296-engines-available-engines

engines:
#  eslint:
#    enabled: true
  scss-lint:
    enabled: true
    checks:
      Comment:
        enabled: false
      UrlFormat:
        enabled: false
  phpmd:
    enabled: true
#  phpcodesniffer:
#    enabled: true

ratings:
   paths:
   - "src/**"

exclude_paths:
   - "tasks/**"
   - "src/assets/images/**"
   - "src/assets/js/vendor/**"
   - "Gruntfile.js"
   - "LICENSE.md"
   - "README.md"
   - "package.json"
