# For a list of all available engines, see here:
# http://docs.codeclimate.com/article/296-engines-available-engines

engines:
#  eslint:
#    enabled: true
  scss-lint:
    enabled: true
    checks:
      Comment:
        enabled: true
        allowed: '^[/* ]*Copyright'
      Indentation:
        width: 4
      SelectorFormat:
        convention: camel_case
      SpaceBeforeBrace:
        allow_single_line_padding: true
      TrailingZero:
        enabled: true
      TransitionAll:
        enabled: true
      UrlFormat:
        enabled: false
  phpmd:
    enabled: true
#  phpcodesniffer:
#    enabled: true

ratings:
   paths:
   - "src/**"

exclude_paths:
   - "tasks/**"
   - "src/assets/images/**"
   - "src/assets/js/vendor/**"
   - "Gruntfile.js"
   - "LICENSE.md"
   - "README.md"
   - "package.json"
